#!/usr/bash
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<"
echo ">>                                                      <<"
echo ">>                  Banco Shell Script                  <<"
echo ">>                                                      <<"
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<"
	echo "Informe seu usuario"
	read usuario
	echo "                                      

	echo "Buscando informações..."
	wget  https://raw.githubusercontent.com/leandersonandre/shell-script/master/lista_usuarios.txt
	resultado=$(cat lista_usuarios.txt | grep -w "$usuario")

	if [ $resultado ]; then
    		echo "Usuário encontrado.\nBaixando dados do usuário..."
    		wget https://github.com/leandersonandre/shell-script/blob/master/$usuario.tar.gz?raw=true | tar -xf
   
	echo "Fazendo o download..."
	echo "Download Completo!"
    
	cd $usuario
    	opcao=0
    
   	 while [ $opcao-ne 3 ]; do
        	echo -e "Escolha uma opção:\n Opção 1: Ver Saldo.\n Opção 2: Ver Extrato.\n Opção 3: Sair.\n Digite a opção escolhida: "
        	read opcao
    	if [ $opcao -eq 1 ]; then
            cat saldo.txt
        elif [ $opcao -eq 2 ]; then
            cat extrato.txt
      	elif [ $opcao -eq 3 ]; then
            echo "Saindo do bank shell..."
        else
            echo "Opção invalida"
        fi
    done
else
    echo "Usuário não encontrado"
fi
fi
